# Use the official Node.js image for Node 22
FROM node:22.8.0

# Set the working directory
WORKDIR /auth

# Copy package.json and package-lock.json
COPY ./backend-auth/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY ./backend-auth .

# Expose port 3000
EXPOSE 3000

# Install nodemon globally
RUN npm install -g nodemon

# Start the application with nodemon
CMD ["nodemon", "./src/server.js"]
