# Use a Node.js image
FROM node:18

# Set the working directory
WORKDIR /app

# Copy the package.json and yarn.lock files for caching layers
COPY ../frontend/package.json ../frontend/yarn.lock ./

# Install dependencies using Yarn
RUN yarn

# Copy the rest of the application files
COPY ../frontend/ .

# Expose the port used by Vite
EXPOSE 5173

# Command to run the Vite development server
CMD ["yarn", "dev"]
